/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisplacas;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Placa;
import servico.PlacaServico;

/**
 *
 * @author usuario
 */
public class ListaPlacas extends javax.swing.JFrame {

    /**
     * Creates new form ListaPlacas
     */
    public ListaPlacas() {
        initComponents();
        
        DefaultTableModel model = new DefaultTableModel();
        
        Object[] columnsName = new Object[3];
        
        columnsName[0] = "Id";
        columnsName[1] = "Descricao";
        columnsName[2] = "Número";
        
        model.setColumnIdentifiers(columnsName);
        
        Object[] rowData = new Object[3];
        
        PlacaServico ps = new PlacaServico();
        List<Placa> placas = ps.findAll();
        
        for(int i = 0; i < placas.size(); i++){
            
            rowData[0] = placas.get(i).getId();
             rowData[1] = placas.get(i).getDescricao();
              rowData[2] = placas.get(i).getNumero();
               
               model.addRow(rowData);
        }
        
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        sisPlacasPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("sisPlacasPU").createEntityManager();
        placaQuery = java.beans.Beans.isDesignTime() ? null : sisPlacasPUEntityManager.createQuery("SELECT p FROM Placa p");
        placaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : placaQuery.getResultList();
        placaQuery1 = java.beans.Beans.isDesignTime() ? null : sisPlacasPUEntityManager.createQuery("SELECT p FROM Placa p");
        placaList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : placaQuery1.getResultList();
        placaQuery2 = java.beans.Beans.isDesignTime() ? null : sisPlacasPUEntityManager.createQuery("SELECT p FROM Placa p");
        placaList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : placaQuery2.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, placaList2, jTable1);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPlacas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<modelo.Placa> placaList;
    private java.util.List<modelo.Placa> placaList1;
    private java.util.List<modelo.Placa> placaList2;
    private javax.persistence.Query placaQuery;
    private javax.persistence.Query placaQuery1;
    private javax.persistence.Query placaQuery2;
    private javax.persistence.EntityManager sisPlacasPUEntityManager;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
